version: '3.7'
services:
  nginx-gin-rest:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 8080:80
    depends_on:
      - ${API_NAME}
      - postgres-gin-rest
    networks:
      - gin-rest-network

  postgres-gin-rest:
    image: postgres:latest
    container_name: postgres-gin-rest
    restart: always
    environment:
      POSTGRES_USER: api_user
      POSTGRES_PASSWORD: api_pass
      POSTGRES_DB: api_gin_rest_db
    ports:
      - "5432:5432"
    volumes:
      - ${PWD}/postgres-data:/var/lib/postgresql/data  
    networks:
      - gin-rest-network

  api-gin-rest:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${API_NAME}
    environment:
      DATABASE_HOST: postgres-gin-rest
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - postgres-gin-rest
    volumes:
      - ${PWD}:/usr/src/app
    command: go run main.go -b 0.0.0.0
    tty: true
    networks:
      - gin-rest-network

  gatling-api-test:
    build:
      context: ./tests/gatling
      dockerfile: Dockerfile
    container_name:
      gatling-api-test
    env_file: 
      - .env
    ports:
      - "${TEST_GATLING_PORT}:${TEST_GATLING_PORT}"
    depends_on:
      - nginx-gin-rest
      - api-gin-rest
      - postgres-gin-rest
    volumes:
      - ${PWD}/tests/gatling:/usr/src/app
    networks:
      - gin-rest-network
      
networks:
  gin-rest-network: