// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://github.com/jtonynet/api-gin-rest",
        "contact": {
            "name": "API GIN Support",
            "url": "https://github.com/jtonynet/api-gin-rest",
            "email": "learningingenuity@gmail.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/aluno": {
            "post": {
                "description": "Cria novo aluno",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Aluno"
                ],
                "summary": "Cria novo aluno",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Aluno"
                        }
                    },
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "type": "uuid"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/aluno/cpf/{cpf}": {
            "get": {
                "description": "Busca aluno por CPF",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Aluno"
                ],
                "summary": "Busca aluno por CPF",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Aluno"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/aluno/uuid/{uuid}": {
            "get": {
                "description": "Busca aluno por id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Aluno"
                ],
                "summary": "Busca aluno por id",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Aluno"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/aluno/{id}": {
            "get": {
                "description": "Busca aluno por id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Aluno"
                ],
                "summary": "Busca aluno por id",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Aluno"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deleta aluno por id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Aluno"
                ],
                "summary": "Deleta aluno por id",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "patch": {
                "description": "Edita aluno por id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Aluno"
                ],
                "summary": "Edita aluno por id",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Aluno"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/alunos": {
            "get": {
                "description": "Obtém a lista completa de alunos",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Alunos"
                ],
                "summary": "Retorna todos os alunos",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Aluno"
                            }
                        }
                    }
                }
            }
        },
        "/alunos/count": {
            "get": {
                "description": "Busca o número de alunos no banco de dados",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Aluno"
                ],
                "summary": "Busca o número de alunos no banco de dados",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "integer"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Aluno": {
            "type": "object",
            "properties": {
                "cpf": {
                    "type": "string",
                    "example": "00000000000"
                },
                "nome": {
                    "type": "string",
                    "example": "Jonh Doe"
                },
                "rg": {
                    "type": "string",
                    "example": "12345678901234"
                },
                "uuid": {
                    "type": "string",
                    "example": "00000000-a0a0-0aa0-0aa0-a0aa0000a000"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0.3",
	Host:             "localhost:8080",
	BasePath:         "/alunos",
	Schemes:          []string{"http"},
	Title:            "api-gin-rest",
	Description:      "Estudo API Rest em Golang com Gin",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
