definitions:
  models.Aluno:
    properties:
      cpf:
        description: para fins de teste de carga, não valido e nem considero esse
          campo como unique
        example: "00000000000"
        type: string
      nome:
        example: Jonh Doe
        type: string
      rg:
        description: para fins de teste de carga, não valido e nem considero esse
          campo como unique
        example: "12345678901234"
        type: string
      uuid:
        example: db047cc5-193a-4989-93f7-08b81c83eea0
        type: string
    required:
    - cpf
    - nome
    - rg
    type: object
info:
  contact: {}
paths:
  /aluno:
    post:
      consumes:
      - application/json
      description: Cria novo aluno
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Aluno'
        "202":
          description: Accepted
          schema:
            type: uuid
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Cria novo aluno
      tags:
      - Aluno
  /aluno/{uuid}:
    delete:
      description: Deleta aluno por uuid
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Deleta aluno por uuid
      tags:
      - Aluno
    get:
      description: Busca aluno por uuid
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Aluno'
        "404":
          description: Not Found
          schema:
            type: string
      summary: Busca aluno por uuid
      tags:
      - Aluno
    patch:
      consumes:
      - application/json
      description: Edita aluno por uuid
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            type: uuid
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Edita aluno por uuid
      tags:
      - Aluno
  /aluno/cpf/{cpf}:
    get:
      description: Busca aluno por CPF
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Aluno'
        "404":
          description: Not Found
          schema:
            type: string
      summary: Busca aluno por CPF
      tags:
      - Aluno
  /alunos:
    get:
      description: Obtém a lista completa de alunos
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Aluno'
            type: array
      summary: Retorna todos os alunos
      tags:
      - Alunos
  /alunos/count:
    get:
      description: Busca o número de alunos no banco de dados
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
      summary: Busca o número de alunos no banco de dados
      tags:
      - Aluno
swagger: "2.0"
